services:
  ubuntu-dev:
    build:
      context: .
    container_name: ubuntu-dev-systemd
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/dbus:/run/dbus:ro
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - ./workspace:/mnt
    command: /sbin/init
    restart: unless-stopped
